CREATE TABLE public.users (
                                id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                created_at timestamp NOT NULL,
                                first_name varchar(255) NULL,
                                last_name varchar(255) NULL,
                                username varchar(255) NOT NULL,
                                organisation varchar(255) NOT NULL,
                                CONSTRAINT user_pkey PRIMARY KEY (id),
                                CONSTRAINT uk_username UNIQUE ("username")
);