CREATE TABLE public.events (
                              id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              name varchar(50) NOT NULL,
                              CONSTRAINT event_pkey PRIMARY KEY (id),
                              CONSTRAINT uk_event_name UNIQUE ("name")
);