CREATE TABLE public.users_events (
                              id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              created_at timestamp NOT NULL,
                              event_id int8 NOT NULL,
                              user_id int8 NOT NULL,
                              CONSTRAINT users_events_pkey PRIMARY KEY (id)
);

ALTER TABLE public.users_events ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.users_events ADD CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events(id);